#!/usr/bin/env bash
#MISE description="Clear cache directories"

find . -name ".react-router" -type d -exec rm -rf {} +
find . -name ".turbo" -type d -exec rm -rf {} +
find . -name ".vitest-attachments" -type d -exec rm -rf {} +
find . -name ".wrangler" -type d -exec rm -rf {} +
find . -name "node_modules" -type d -exec rm -rf {} +
