#!/usr/bin/env bash
#MISE description="Clear cache directories"

cd "$MISE_ORIGINAL_CWD"

find . -name ".knip" -type d -exec rm -rf {} +
find . -name ".react-router" -type d -exec rm -rf {} +
find . -name ".turbo" -type d -exec rm -rf {} +
find . -name ".wrangler" -type d -exec rm -rf {} +
find . -name "build" -type d -exec rm -rf {} +
find . -name "dist" -type d -exec rm -rf {} +
find . -name "node_modules" -type d -exec rm -rf {} +
