# https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️ "
      prefix-development: "⬆️ "
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️ "
      prefix-development: "⬆️ "
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"
      - "npm"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️ "
      prefix-development: "⬆️ "
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"
      - "docker"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆️ "
      prefix-development: "⬆️ "
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"
      - "docker-compose"
