services:
  linux-vrt:
    build:
      context: .
      dockerfile: .docker/linux-vrt/Dockerfile
    volumes:
      # Mount entire project for dynamic source code updates
      - .:/app
      # Protect node_modules from being overwritten by host
      - /app/node_modules
      - /app/apps/roppoh/node_modules
      - /app/packages/better-auth-database/node_modules
    command: bun run test:visual --update
