[tools]
bun = "1.3.12"
lefthook = "latest"
"npm:turbo" = "latest"
"npm:@dotenvx/dotenvx" = "latest"

[settings]
npm.bun = true

[tasks.format]
run = "bun run oxfmt"

[tasks.update-vrt-screenshots]
description = "Update VRT screenshots"
run = [
  "docker compose up -d --remove-orphans --build",
  "docker compose exec linux-vrt sh -c 'cd apps/roppoh && bun run test:visual --update'",
  "docker compose exec linux-vrt sh -c 'cd apps/ura-roppoh && bun run test:visual --update'",
  "docker compose down --remove-orphans --volumes",
]
