import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  ignorePatterns: [
    "apps/emdash/src",
    "packages/shadcn/src",
    "**/worker-configuration.d.ts",
    "packages/domain/src",
  ],
  options: {
    typeAware: true,
    typeCheck: true,
  },
  rules: {
    "eslint/no-unused-vars": "error",
    "eslint/sort-imports": "off",
    "func-names": "off",
    "func-style": "off",
    "id-length": "off",
    "max-params": "off",
    "no-console": "off",
    "no-duplicate-imports": "off",
    "no-empty-function": "off",
    "no-magic-numbers": "off",
    "no-ternary": "off",
    "no-undefined": "off",
    "no-void": "off",
    "oxc/no-async-await": "off",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-module-boundary-types": "off",
    "unicorn/no-anonymous-default-export": "off",
    "unicorn/no-null": "off",
    "sort-keys": "off",
    "new-cap": "off",
  },
});
