#!/usr/bin/env bash
#MISE description="Update all VRT screenshots"

set -euo pipefail

mise run test:vrt:neo-fujimatsu -- --update-snapshots
mise run test:vrt:roppoh -- --update-snapshots
mise run test:vrt:ura-roppoh -- --update-snapshots
