#!/usr/bin/env bash
#MISE description="Run VRT for @roppoh/ura-roppoh"
#MISE depends=["test:vrt:build-container"]
#USAGE flag "-u --update-snapshots" help="Update VRT screenshots"

set -euo pipefail

IMAGE="roppoh-playwright:latest"

CMD="bun run --filter @roppoh/ura-roppoh test:visual"
if [ "${usage_update_snapshots:-false}" = "true" ]; then
  CMD+=" -- --update-snapshots"
fi

docker run --rm \
  -v "$PWD/apps/ura-roppoh/test/visual-regression":/app/apps/ura-roppoh/test/visual-regression \
  "$IMAGE" \
  bash -c "$CMD"
