-- Super Admin User Seeder
-- Creates a super-admin user for development and testing purposes
--
-- Credentials:
--   Email: super-admin@tsar-bmb.org
--   Password: password
--   Role: super-admin
--
-- IMPORTANT: Change the password after first login in production!
--
-- NOTE: This SQL uses actual password hash generated by better-auth.
--       The hash format is "salt:hash" which is better-auth's internal format.
--       Password: "password"

-- Insert super-admin user
INSERT INTO user (
  id,
  email,
  name,
  role,
  email_verified,
  banned,
  ban_expires,
  ban_reason,
  image,
  created_at,
  updated_at
) VALUES (
  'super-admin-seed-001',
  'super-admin@tsar-bmb.org',
  'Super Administrator',
  'admin',
  1, -- true (email_verified)
  0, -- false (banned)
  NULL,
  NULL,
  NULL,
  cast(unixepoch('subsecond') * 1000 as integer),
  cast(unixepoch('subsecond') * 1000 as integer)
);

-- Insert credential account for the super-admin user
-- Password hash format: salt:hash (better-auth internal format)
-- This hash was generated by better-auth for the password "password"
INSERT INTO account (
  id,
  user_id,
  account_id,
  provider_id,
  password,
  access_token,
  access_token_expires_at,
  id_token,
  refresh_token,
  refresh_token_expires_at,
  scope,
  created_at,
  updated_at
) VALUES (
  'super-admin-account-seed-001',
  'super-admin-seed-001',
  'super-admin-seed-001', -- account_id MUST equal user_id for credential accounts
  'credential', -- provider_id for email/password authentication
  '86042285894f79184913afed7ba4343e:0acc6b40b651fe59435650da76e321b066c20e865308794c49557d5a9078446ccfefa4cc5ef1f3980b380b02bcc25ae86098a2b625fabd6f88c95a9e6308aaa9', -- better-auth hash for "password"
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  cast(unixepoch('subsecond') * 1000 as integer),
  cast(unixepoch('subsecond') * 1000 as integer)
);
