/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";

import type { NHttp400Response, NHttp401Response } from ".././model";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * Get all resources.
 * @summary List
 */
export type listResourcesResponse200 = {
  data: string;
  status: 200;
};

export type listResourcesResponse400 = {
  data: NHttp400Response;
  status: 400;
};

export type listResourcesResponse401 = {
  data: NHttp401Response;
  status: 401;
};

export type listResourcesResponseSuccess = listResourcesResponse200 & {
  headers: Headers;
};
export type listResourcesResponseError = (
  | listResourcesResponse400
  | listResourcesResponse401
) & {
  headers: Headers;
};

export type listResourcesResponse =
  | listResourcesResponseSuccess
  | listResourcesResponseError;

export const getListResourcesUrl = () => {
  return `https://coolify.tsar-bmb.org/resources`;
};

export const listResources = async (
  options?: RequestInit,
): Promise<listResourcesResponse> => {
  const res = await fetch(getListResourcesUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listResourcesResponse["data"] = body ? JSON.parse(body) : {};
  return {
    data,
    headers: res.headers,
    status: res.status,
  } as listResourcesResponse;
};

export const getListResourcesQueryKey = () => {
  return [`https://coolify.tsar-bmb.org/resources`] as const;
};

export const getListResourcesQueryOptions = <
  TData = Awaited<ReturnType<typeof listResources>>,
  TError = NHttp400Response | NHttp401Response,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof listResources>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListResourcesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listResources>>> = ({
    signal,
  }) => listResources({ signal, ...fetchOptions });

  return { queryFn, queryKey, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listResources>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListResourcesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listResources>>
>;
export type ListResourcesQueryError = NHttp400Response | NHttp401Response;

export function useListResources<
  TData = Awaited<ReturnType<typeof listResources>>,
  TError = NHttp400Response | NHttp401Response,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listResources>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listResources>>,
          TError,
          Awaited<ReturnType<typeof listResources>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListResources<
  TData = Awaited<ReturnType<typeof listResources>>,
  TError = NHttp400Response | NHttp401Response,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listResources>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listResources>>,
          TError,
          Awaited<ReturnType<typeof listResources>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListResources<
  TData = Awaited<ReturnType<typeof listResources>>,
  TError = NHttp400Response | NHttp401Response,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listResources>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List
 */

export function useListResources<
  TData = Awaited<ReturnType<typeof listResources>>,
  TError = NHttp400Response | NHttp401Response,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listResources>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListResourcesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
