// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales = "ar" | "en" | "ja-JP";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  login: {
    /**
     * L​o​g​i​n​ ​w​i​t​h​ ​D​i​s​c​o​r​d
     */
    loginButton: string;
    /**
     * T​h​e​ ​g​a​m​e​ ​s​e​r​v​e​r​ ​m​a​n​a​g​e​m​e​n​t​ ​w​e​b​ ​a​p​p​l​i​c​a​t​i​o​n​.​ ​A​n​d​ ​P​l​a​y​ ​W​e​b​G​L​ ​g​a​m​e​s​ ​r​i​g​h​t​ ​i​n​ ​y​o​u​r​ ​b​r​o​w​s​e​r
     */
    description: string;
  };
  sidebar: {
    content: {
      /**
       * I​t​e​m​s
       */
      items: string;
      /**
       * P​l​a​y​g​r​o​u​n​d
       */
      playground: string;
      /**
       * S​e​r​v​e​r​s
       */
      servers: string;
    };
    userNavigation: {
      /**
       * L​o​g​ ​o​u​t
       */
      logOut: string;
      theme: {
        /**
         * T​o​g​g​l​e​ ​t​h​e​m​e
         */
        toggleTheme: string;
        /**
         * D​a​r​k
         */
        dark: string;
        /**
         * L​i​g​h​t
         */
        light: string;
      };
    };
  };
  top: {
    /**
     * S​e​r​v​e​r​s
     */
    title: string;
    tile: {
      unitySportsResortCard: {
        /**
         * P​l​a​y
         */
        play: string;
        /**
         * A​u​t​h​o​r​:​
         */
        author: string;
      };
    };
    table: {
      customizeColumns: {
        /**
         * C​u​s​t​o​m​i​z​e​ ​C​o​l​u​m​n​s
         */
        long: string;
        /**
         * C​o​l​u​m​n​s
         */
        short: string;
      };
      column: {
        /**
         * C​o​m​p​o​s​e​ ​N​a​m​e
         */
        composeName: string;
        /**
         * P​r​o​j​e​c​t
         */
        project: string;
        /**
         * E​n​v​i​r​o​n​m​e​n​t
         */
        environment: string;
        /**
         * S​t​a​t​u​s
         */
        status: string;
        /**
         * T​y​p​e
         */
        type: string;
        /**
         * D​e​s​c​r​i​p​t​i​o​n
         */
        description: string;
      };
      serverActionDropdown: {
        start: {
          /**
           * S​t​a​r​t
           */
          start: string;
          /**
           * ❌​ ​F​a​i​l​e​d​ ​t​o​ ​s​t​a​r​t​ ​s​e​r​v​e​r​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
           */
          error: string;
          /**
           * �​�​ ​L​a​u​n​c​h​i​n​g​ ​s​e​r​v​e​r​.​.​.
           */
          loading: string;
          /**
           * ✨​ ​S​e​r​v​e​r​ ​i​s​ ​u​p​ ​a​n​d​ ​r​u​n​n​i​n​g​!
           */
          success: string;
        };
        stop: {
          /**
           * S​t​o​p
           */
          stop: string;
          /**
           * ❌​ ​F​a​i​l​e​d​ ​t​o​ ​s​t​o​p​ ​s​e​r​v​e​r​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
           */
          error: string;
          /**
           * ⏹​️​ ​S​t​o​p​p​i​n​g​ ​s​e​r​v​e​r​.​.​.
           */
          loading: string;
          /**
           * ✅​ ​S​e​r​v​e​r​ ​s​t​o​p​p​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
           */
          success: string;
        };
        redeploy: {
          /**
           * R​e​D​e​p​l​o​y
           */
          reDeploy: string;
          /**
           * ❌​ ​F​a​i​l​e​d​ ​t​o​ ​r​e​d​e​p​l​o​y​ ​s​e​r​v​e​r​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
           */
          error: string;
          /**
           * �​�​ ​R​e​d​e​p​l​o​y​i​n​g​ ​s​e​r​v​e​r​.​.​.
           */
          loading: string;
          /**
           * �​�​ ​S​e​r​v​e​r​ ​r​e​d​e​p​l​o​y​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
           */
          success: string;
        };
      };
      pagination: {
        /**
         * {​s​e​l​e​c​t​e​d​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​r​o​w​(​s​)​ ​s​e​l​e​c​t​e​d
         * @param {unknown} selected
         * @param {unknown} total
         */
        rowsSelected: RequiredParams<"selected" | "total">;
        /**
         * P​a​g​e​ ​{​c​u​r​r​e​n​t​}​ ​o​f​ ​{​t​o​t​a​l​}
         * @param {unknown} current
         * @param {unknown} total
         */
        pageInfo: RequiredParams<"current" | "total">;
      };
    };
  };
  unitySportsResortCard: {
    /**
     * P​l​a​y
     */
    play: string;
  };
};

export type TranslationFunctions = {
  login: {
    /**
     * Login with Discord
     */
    loginButton: () => LocalizedString;
    /**
     * The game server management web application. And Play WebGL games right in your browser
     */
    description: () => LocalizedString;
  };
  sidebar: {
    content: {
      /**
       * Items
       */
      items: () => LocalizedString;
      /**
       * Playground
       */
      playground: () => LocalizedString;
      /**
       * Servers
       */
      servers: () => LocalizedString;
    };
    userNavigation: {
      /**
       * Log out
       */
      logOut: () => LocalizedString;
      theme: {
        /**
         * Toggle theme
         */
        toggleTheme: () => LocalizedString;
        /**
         * Dark
         */
        dark: () => LocalizedString;
        /**
         * Light
         */
        light: () => LocalizedString;
      };
    };
  };
  top: {
    /**
     * Servers
     */
    title: () => LocalizedString;
    tile: {
      unitySportsResortCard: {
        /**
         * Play
         */
        play: () => LocalizedString;
        /**
         * Author:
         */
        author: () => LocalizedString;
      };
    };
    table: {
      customizeColumns: {
        /**
         * Customize Columns
         */
        long: () => LocalizedString;
        /**
         * Columns
         */
        short: () => LocalizedString;
      };
      column: {
        /**
         * Compose Name
         */
        composeName: () => LocalizedString;
        /**
         * Project
         */
        project: () => LocalizedString;
        /**
         * Environment
         */
        environment: () => LocalizedString;
        /**
         * Status
         */
        status: () => LocalizedString;
        /**
         * Type
         */
        type: () => LocalizedString;
        /**
         * Description
         */
        description: () => LocalizedString;
      };
      serverActionDropdown: {
        start: {
          /**
           * Start
           */
          start: () => LocalizedString;
          /**
           * ❌ Failed to start server. Please try again.
           */
          error: () => LocalizedString;
          /**
           * 🚀 Launching server...
           */
          loading: () => LocalizedString;
          /**
           * ✨ Server is up and running!
           */
          success: () => LocalizedString;
        };
        stop: {
          /**
           * Stop
           */
          stop: () => LocalizedString;
          /**
           * ❌ Failed to stop server. Please try again.
           */
          error: () => LocalizedString;
          /**
           * ⏹️ Stopping server...
           */
          loading: () => LocalizedString;
          /**
           * ✅ Server stopped successfully
           */
          success: () => LocalizedString;
        };
        redeploy: {
          /**
           * ReDeploy
           */
          reDeploy: () => LocalizedString;
          /**
           * ❌ Failed to redeploy server. Please try again.
           */
          error: () => LocalizedString;
          /**
           * 🔄 Redeploying server...
           */
          loading: () => LocalizedString;
          /**
           * 🎉 Server redeployed successfully!
           */
          success: () => LocalizedString;
        };
      };
      pagination: {
        /**
         * {selected} of {total} row(s) selected
         */
        rowsSelected: (arg: { selected: unknown; total: unknown }) => LocalizedString;
        /**
         * Page {current} of {total}
         */
        pageInfo: (arg: { current: unknown; total: unknown }) => LocalizedString;
      };
    };
  };
  unitySportsResortCard: {
    /**
     * Play
     */
    play: () => LocalizedString;
  };
};

export type Formatters = {};
