/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

/**
 * Build pack.
 */
export type ApplicationDTOBuildPack =
  (typeof ApplicationDTOBuildPack)[keyof typeof ApplicationDTOBuildPack];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApplicationDTOBuildPack = {
  dockercompose: "dockercompose",
  dockerfile: "dockerfile",
  nixpacks: "nixpacks",
  static: "static",
} as const;
