/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { ApplicationDTOBuildPack } from "./application-dto-build-pack";
import type { ApplicationDTORedirect } from "./application-dto-redirect";

/**
 * Application model
 */
export interface ApplicationDTO {
  /** The application identifier in the database. */
  id?: number;
  /**
   * The application description.
   * @nullable
   */
  description?: string | null;
  /**
   * The repository project identifier.
   * @nullable
   */
  repository_project_id?: number | null;
  /** The application UUID. */
  uuid?: string;
  /** The application name. */
  name?: string;
  /**
   * The application domains.
   * @nullable
   */
  fqdn?: string | null;
  /** Configuration hash. */
  config_hash?: string;
  /** Git repository URL. */
  git_repository?: string;
  /** Git branch. */
  git_branch?: string;
  /** Git commit SHA. */
  git_commit_sha?: string;
  /**
   * Git full URL.
   * @nullable
   */
  git_full_url?: string | null;
  /**
   * Docker registry image name.
   * @nullable
   */
  docker_registry_image_name?: string | null;
  /**
   * Docker registry image tag.
   * @nullable
   */
  docker_registry_image_tag?: string | null;
  /** Build pack. */
  build_pack?: ApplicationDTOBuildPack;
  /** Static image used when static site is deployed. */
  static_image?: string;
  /** Install command. */
  install_command?: string;
  /** Build command. */
  build_command?: string;
  /** Start command. */
  start_command?: string;
  /** Ports exposes. */
  ports_exposes?: string;
  /**
   * Ports mappings.
   * @nullable
   */
  ports_mappings?: string | null;
  /**
   * Network aliases for Docker container.
   * @nullable
   */
  custom_network_aliases?: string | null;
  /** Base directory for all commands. */
  base_directory?: string;
  /** Publish directory. */
  publish_directory?: string;
  /** Health check enabled. */
  health_check_enabled?: boolean;
  /** Health check path. */
  health_check_path?: string;
  /**
   * Health check port.
   * @nullable
   */
  health_check_port?: string | null;
  /**
   * Health check host.
   * @nullable
   */
  health_check_host?: string | null;
  /** Health check method. */
  health_check_method?: string;
  /** Health check return code. */
  health_check_return_code?: number;
  /** Health check scheme. */
  health_check_scheme?: string;
  /**
   * Health check response text.
   * @nullable
   */
  health_check_response_text?: string | null;
  /** Health check interval in seconds. */
  health_check_interval?: number;
  /** Health check timeout in seconds. */
  health_check_timeout?: number;
  /** Health check retries count. */
  health_check_retries?: number;
  /** Health check start period in seconds. */
  health_check_start_period?: number;
  /** Memory limit. */
  limits_memory?: string;
  /** Memory swap limit. */
  limits_memory_swap?: string;
  /** Memory swappiness. */
  limits_memory_swappiness?: number;
  /** Memory reservation. */
  limits_memory_reservation?: string;
  /** CPU limit. */
  limits_cpus?: string;
  /**
   * CPU set.
   * @nullable
   */
  limits_cpuset?: string | null;
  /** CPU shares. */
  limits_cpu_shares?: number;
  /** Application status. */
  status?: string;
  /** Preview URL template. */
  preview_url_template?: string;
  /** Destination type. */
  destination_type?: string;
  /** Destination identifier. */
  destination_id?: number;
  /**
   * Source identifier.
   * @nullable
   */
  source_id?: number | null;
  /**
   * Private key identifier.
   * @nullable
   */
  private_key_id?: number | null;
  /** Environment identifier. */
  environment_id?: number;
  /**
   * Dockerfile content. Used for dockerfile build pack.
   * @nullable
   */
  dockerfile?: string | null;
  /** Dockerfile location. */
  dockerfile_location?: string;
  /**
   * Custom labels.
   * @nullable
   */
  custom_labels?: string | null;
  /**
   * Dockerfile target build.
   * @nullable
   */
  dockerfile_target_build?: string | null;
  /**
   * Manual webhook secret for GitHub.
   * @nullable
   */
  manual_webhook_secret_github?: string | null;
  /**
   * Manual webhook secret for GitLab.
   * @nullable
   */
  manual_webhook_secret_gitlab?: string | null;
  /**
   * Manual webhook secret for Bitbucket.
   * @nullable
   */
  manual_webhook_secret_bitbucket?: string | null;
  /**
   * Manual webhook secret for Gitea.
   * @nullable
   */
  manual_webhook_secret_gitea?: string | null;
  /** Docker compose location. */
  docker_compose_location?: string;
  /**
   * Docker compose content. Used for docker compose build pack.
   * @nullable
   */
  docker_compose?: string | null;
  /**
   * Docker compose raw content.
   * @nullable
   */
  docker_compose_raw?: string | null;
  /**
   * Docker compose domains.
   * @nullable
   */
  docker_compose_domains?: string | null;
  /**
   * Docker compose custom start command.
   * @nullable
   */
  docker_compose_custom_start_command?: string | null;
  /**
   * Docker compose custom build command.
   * @nullable
   */
  docker_compose_custom_build_command?: string | null;
  /**
   * Swarm replicas. Only used for swarm deployments.
   * @nullable
   */
  swarm_replicas?: number | null;
  /**
   * Swarm placement constraints. Only used for swarm deployments.
   * @nullable
   */
  swarm_placement_constraints?: string | null;
  /**
   * Custom docker run options.
   * @nullable
   */
  custom_docker_run_options?: string | null;
  /**
   * Post deployment command.
   * @nullable
   */
  post_deployment_command?: string | null;
  /**
   * Post deployment command container.
   * @nullable
   */
  post_deployment_command_container?: string | null;
  /**
   * Pre deployment command.
   * @nullable
   */
  pre_deployment_command?: string | null;
  /**
   * Pre deployment command container.
   * @nullable
   */
  pre_deployment_command_container?: string | null;
  /**
   * Watch paths.
   * @nullable
   */
  watch_paths?: string | null;
  /** Custom healthcheck found. */
  custom_healthcheck_found?: boolean;
  /**
   * How to set redirect with Traefik / Caddy. www<->non-www.
   * @nullable
   */
  redirect?: ApplicationDTORedirect;
  /** The date and time when the application was created. */
  created_at?: string;
  /** The date and time when the application was last updated. */
  updated_at?: string;
  /**
   * The date and time when the application was deleted.
   * @nullable
   */
  deleted_at?: string | null;
  /** How Coolify parse the compose file. */
  compose_parsing_version?: string;
  /**
   * Custom Nginx configuration base64 encoded.
   * @nullable
   */
  custom_nginx_configuration?: string | null;
  /** HTTP Basic Authentication enabled. */
  is_http_basic_auth_enabled?: boolean;
  /**
   * Username for HTTP Basic Authentication
   * @nullable
   */
  http_basic_auth_username?: string | null;
  /**
   * Password for HTTP Basic Authentication
   * @nullable
   */
  http_basic_auth_password?: string | null;
}
