/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type CreateDatabaseKeydbBodies = {
  /** UUID of the server */
  server_uuid: string;
  /** UUID of the project */
  project_uuid: string;
  /** Name of the environment. You need to provide at least one of environment_name or environment_uuid. */
  environment_name: string;
  /** UUID of the environment. You need to provide at least one of environment_name or environment_uuid. */
  environment_uuid: string;
  /** UUID of the destination if the server has multiple destinations */
  destination_uuid?: string;
  /** KeyDB password */
  keydb_password?: string;
  /** KeyDB conf */
  keydb_conf?: string;
  /** Name of the database */
  name?: string;
  /** Description of the database */
  description?: string;
  /** Docker Image of the database */
  image?: string;
  /** Is the database public? */
  is_public?: boolean;
  /** Public port of the database */
  public_port?: number;
  /** Memory limit of the database */
  limits_memory?: string;
  /** Memory swap limit of the database */
  limits_memory_swap?: string;
  /** Memory swappiness of the database */
  limits_memory_swappiness?: number;
  /** Memory reservation of the database */
  limits_memory_reservation?: string;
  /** CPU limit of the database */
  limits_cpus?: string;
  /** CPU set of the database */
  limits_cpuset?: string;
  /** CPU shares of the database */
  limits_cpu_shares?: number;
  /** Instant deploy the database */
  instant_deploy?: boolean;
};
