/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { CreatePrivateDeployKeyApplication409ConflictsSchema } from "./create-private-deploy-key-application409-conflicts-schema";

export type CreatePrivateDeployKeyApplication409 = {
  message?: string;
  warning?: string;
  conflicts?: CreatePrivateDeployKeyApplication409ConflictsSchema[];
};
