/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { CreatePrivateDeployKeyApplication409ConflictsSchemaResourceType } from "./create-private-deploy-key-application409-conflicts-schema-resource-type";

export type CreatePrivateDeployKeyApplication409ConflictsSchema = {
  domain?: string;
  resource_name?: string;
  /** @nullable */
  resource_uuid?: string | null;
  resource_type?: CreatePrivateDeployKeyApplication409ConflictsSchemaResourceType;
  message?: string;
};
