/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

/**
 * How to set redirect with Traefik / Caddy. www<->non-www.
 * @nullable
 */
export type CreatePrivateDeployKeyApplicationBodiesRedirect =
  | (typeof CreatePrivateDeployKeyApplicationBodiesRedirect)[keyof typeof CreatePrivateDeployKeyApplicationBodiesRedirect]
  | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePrivateDeployKeyApplicationBodiesRedirect = {
  both: "both",
  "non-www": "non-www",
  www: "www",
} as const;
