/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type CreateProjectBodies = {
  /** The name of the project. */
  name?: string;
  /** The description of the project. */
  description?: string;
};
