/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type CreatePrivateDeployKeyApplication409ConflictsSchemaResourceType =
  (typeof CreatePrivateDeployKeyApplication409ConflictsSchemaResourceType)[keyof typeof CreatePrivateDeployKeyApplication409ConflictsSchemaResourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePrivateDeployKeyApplication409ConflictsSchemaResourceType = {
  application: "application",
  instance: "instance",
  service: "service",
} as const;
