/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type CreateDockerfileApplication409ConflictsSchemaResourceType =
  (typeof CreateDockerfileApplication409ConflictsSchemaResourceType)[keyof typeof CreateDockerfileApplication409ConflictsSchemaResourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateDockerfileApplication409ConflictsSchemaResourceType = {
  application: "application",
  instance: "instance",
  service: "service",
} as const;
