/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

/**
 * The static image.
 */
export type CreatePrivateGithubAppApplicationBodiesStaticImage =
  (typeof CreatePrivateGithubAppApplicationBodiesStaticImage)[keyof typeof CreatePrivateGithubAppApplicationBodiesStaticImage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePrivateGithubAppApplicationBodiesStaticImage = {
  "nginx:alpine": "nginx:alpine",
} as const;
