/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

/**
 * The build pack type.
 */
export type CreatePublicApplicationBodiesBuildPack =
  (typeof CreatePublicApplicationBodiesBuildPack)[keyof typeof CreatePublicApplicationBodiesBuildPack];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePublicApplicationBodiesBuildPack = {
  dockercompose: "dockercompose",
  dockerfile: "dockerfile",
  nixpacks: "nixpacks",
  static: "static",
} as const;
