/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type CreatePublicApplication409ConflictsSchemaResourceType =
  (typeof CreatePublicApplication409ConflictsSchemaResourceType)[keyof typeof CreatePublicApplication409ConflictsSchemaResourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePublicApplication409ConflictsSchemaResourceType = {
  application: "application",
  instance: "instance",
  service: "service",
} as const;
