/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { CreateDockerimageApplication409ConflictsSchema } from "./create-dockerimage-application409-conflicts-schema";

export type CreateDockerimageApplication409 = {
  message?: string;
  warning?: string;
  conflicts?: CreateDockerimageApplication409ConflictsSchema[];
};
