/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type CreateDockercomposeApplicationBodies = {
  /** The project UUID. */
  project_uuid: string;
  /** The server UUID. */
  server_uuid: string;
  /** The environment name. You need to provide at least one of environment_name or environment_uuid. */
  environment_name: string;
  /** The environment UUID. You need to provide at least one of environment_name or environment_uuid. */
  environment_uuid: string;
  /** The Docker Compose raw content. */
  docker_compose_raw: string;
  /** The destination UUID if the server has more than one destinations. */
  destination_uuid?: string;
  /** The application name. */
  name?: string;
  /** The application description. */
  description?: string;
  /** The flag to indicate if the application should be deployed instantly. */
  instant_deploy?: boolean;
  /**
   * Use build server.
   * @nullable
   */
  use_build_server?: boolean | null;
  /** The flag to connect the service to the predefined Docker network. */
  connect_to_docker_network?: boolean;
  /** Force domain usage even if conflicts are detected. Default is false. */
  force_domain_override?: boolean;
};
