/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { CreateServerBodiesProxyType } from "./create-server-bodies-proxy-type";

export type CreateServerBodies = {
  /** The name of the server. */
  name?: string;
  /** The description of the server. */
  description?: string;
  /** The IP of the server. */
  ip?: string;
  /** The port of the server. */
  port?: number;
  /** The user of the server. */
  user?: string;
  /** The UUID of the private key. */
  private_key_uuid?: string;
  /** Is build server. */
  is_build_server?: boolean;
  /** Instant validate. */
  instant_validate?: boolean;
  /** The proxy type. */
  proxy_type?: CreateServerBodiesProxyType;
};
