/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { CreateDockercomposeApplication409ConflictsSchema } from "./create-dockercompose-application409-conflicts-schema";

export type CreateDockercomposeApplication409 = {
  message?: string;
  warning?: string;
  conflicts?: CreateDockercomposeApplication409ConflictsSchema[];
};
