/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { CreateDockercomposeApplication409ConflictsSchemaResourceType } from "./create-dockercompose-application409-conflicts-schema-resource-type";

export type CreateDockercomposeApplication409ConflictsSchema = {
  domain?: string;
  resource_name?: string;
  /** @nullable */
  resource_uuid?: string | null;
  resource_type?: CreateDockercomposeApplication409ConflictsSchemaResourceType;
  message?: string;
};
