/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { CreateDockerfileApplication409ConflictsSchemaResourceType } from "./create-dockerfile-application409-conflicts-schema-resource-type";

export type CreateDockerfileApplication409ConflictsSchema = {
  domain?: string;
  resource_name?: string;
  /** @nullable */
  resource_uuid?: string | null;
  resource_type?: CreateDockerfileApplication409ConflictsSchemaResourceType;
  message?: string;
};
