/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type CreateDockercomposeApplication409ConflictsSchemaResourceType =
  (typeof CreateDockercomposeApplication409ConflictsSchemaResourceType)[keyof typeof CreateDockercomposeApplication409ConflictsSchemaResourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateDockercomposeApplication409ConflictsSchemaResourceType = {
  application: "application",
  instance: "instance",
  service: "service",
} as const;
