/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

/**
 * The build pack type.
 */
export type CreatePrivateGithubAppApplicationBodiesBuildPack =
  (typeof CreatePrivateGithubAppApplicationBodiesBuildPack)[keyof typeof CreatePrivateGithubAppApplicationBodiesBuildPack];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePrivateGithubAppApplicationBodiesBuildPack = {
  dockercompose: "dockercompose",
  dockerfile: "dockerfile",
  nixpacks: "nixpacks",
  static: "static",
} as const;
