/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

/**
 * The static image.
 */
export type CreatePublicApplicationBodiesStaticImage =
  (typeof CreatePublicApplicationBodiesStaticImage)[keyof typeof CreatePublicApplicationBodiesStaticImage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePublicApplicationBodiesStaticImage = {
  "nginx:alpine": "nginx:alpine",
} as const;
