/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { CreatePublicApplication409ConflictsSchema } from "./create-public-application409-conflicts-schema";

export type CreatePublicApplication409 = {
  message?: string;
  warning?: string;
  conflicts?: CreatePublicApplication409ConflictsSchema[];
};
