/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type DeployByTagOrUuidParams = {
  /**
   * Tag name(s). Comma separated list is also accepted.
   */
  tag?: string;
  /**
   * Resource UUID(s). Comma separated list is also accepted.
   */
  uuid?: string;
  /**
   * Force rebuild (without cache)
   */
  force?: boolean;
  /**
   * Pull Request Id for deploying specific PR builds. Cannot be used with tag parameter.
   */
  pr?: number;
};
