/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type DeployByTagOrUuid200DeploymentsSchema = {
  message?: string;
  resource_uuid?: string;
  deployment_uuid?: string;
};
