/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { DeployByTagOrUuid200DeploymentsSchema } from "./deploy-by-tag-or-uuid200-deployments-schema";

export type DeployByTagOrUuid200 = {
  deployments?: DeployByTagOrUuid200DeploymentsSchema[];
};
