/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

/**
 * Environment model
 */
export interface EnvironmentDTO {
  id?: number;
  name?: string;
  project_id?: number;
  created_at?: string;
  updated_at?: string;
  description?: string;
}
