/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

/**
 * Environment Variable model
 */
export interface EnvironmentVariableDTO {
  id?: number;
  uuid?: string;
  resourceable_type?: string;
  resourceable_id?: number;
  is_literal?: boolean;
  is_multiline?: boolean;
  is_preview?: boolean;
  is_runtime?: boolean;
  is_buildtime?: boolean;
  is_shared?: boolean;
  is_shown_once?: boolean;
  key?: string;
  value?: string;
  real_value?: string;
  version?: string;
  created_at?: string;
  updated_at?: string;
}
