/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type GetApplicationLogsByUuidParams = {
  /**
   * Number of lines to show from the end of the logs.
   */
  lines?: number;
};
