/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type ListDeploymentsByAppUuidParams = {
  /**
   * Number of records to skip.
   * @minimum 0
   */
  skip?: number;
  /**
   * Number of records to take.
   * @minimum 1
   */
  take?: number;
};
