/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { Http400Response } from "./http-400-response";

/**
 * Invalid token.
 */
export type NHttp400Response = Http400Response;
