/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { Http401Response } from "./http-401-response";

/**
 * Unauthenticated.
 */
export type NHttp401Response = Http401Response;
