/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { Http404Response } from "./http-404-response";

/**
 * Resource not found.
 */
export type NHttp404Response = Http404Response;
