/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

/**
 * Private Key model
 */
export interface PrivateKeyDTO {
  id?: number;
  uuid?: string;
  name?: string;
  description?: string;
  private_key?: string;
  /** The public key of the private key. */
  public_key?: string;
  /** The fingerprint of the private key. */
  fingerprint?: string;
  is_git_related?: boolean;
  team_id?: number;
  created_at?: string;
  updated_at?: string;
}
