/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { EnvironmentDTO } from "./environment-dt-o";

/**
 * Project model
 */
export interface ProjectDTO {
  id?: number;
  uuid?: string;
  name?: string;
  description?: string;
  /** The environments of the project. */
  environments?: EnvironmentDTO[];
}
