/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type StartApplicationByUuidParams = {
  /**
   * Force rebuild.
   */
  force?: boolean;
  /**
   * Instant deploy (skip queuing).
   */
  instant_deploy?: boolean;
};
