/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { UserDTO } from "./user-dt-o";

/**
 * Team model
 */
export interface TeamDTO {
  /** The unique identifier of the team. */
  id?: number;
  /** The name of the team. */
  name?: string;
  /** The description of the team. */
  description?: string;
  /** Whether the team is personal or not. */
  personal_team?: boolean;
  /** The date and time the team was created. */
  created_at?: string;
  /** The date and time the team was last updated. */
  updated_at?: string;
  /** Whether to show the boarding screen or not. */
  show_boarding?: boolean;
  /** The custom server limit. */
  custom_server_limit?: string;
  /** The members of the team. */
  members?: UserDTO[];
}
