/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { UpdateApplicationByUuid409ConflictsSchemaResourceType } from "./update-application-by-uuid409-conflicts-schema-resource-type";

export type UpdateApplicationByUuid409ConflictsSchema = {
  domain?: string;
  resource_name?: string;
  /** @nullable */
  resource_uuid?: string | null;
  resource_type?: UpdateApplicationByUuid409ConflictsSchemaResourceType;
  message?: string;
};
