/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type UpdateEnvByServiceUuidBodies = {
  /** The key of the environment variable. */
  key: string;
  /** The value of the environment variable. */
  value: string;
  /** The flag to indicate if the environment variable is used in preview deployments. */
  is_preview?: boolean;
  /** The flag to indicate if the environment variable is a literal, nothing espaced. */
  is_literal?: boolean;
  /** The flag to indicate if the environment variable is multiline. */
  is_multiline?: boolean;
  /** The flag to indicate if the environment variable's value is shown on the UI. */
  is_shown_once?: boolean;
};
