/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type UpdatePrivateKeyBodies = {
  name?: string;
  description?: string;
  private_key: string;
};
