/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type UpdateDatabaseByUuidBodies = {
  /** Name of the database */
  name?: string;
  /** Description of the database */
  description?: string;
  /** Docker Image of the database */
  image?: string;
  /** Is the database public? */
  is_public?: boolean;
  /** Public port of the database */
  public_port?: number;
  /** Memory limit of the database */
  limits_memory?: string;
  /** Memory swap limit of the database */
  limits_memory_swap?: string;
  /** Memory swappiness of the database */
  limits_memory_swappiness?: number;
  /** Memory reservation of the database */
  limits_memory_reservation?: string;
  /** CPU limit of the database */
  limits_cpus?: string;
  /** CPU set of the database */
  limits_cpuset?: string;
  /** CPU shares of the database */
  limits_cpu_shares?: number;
  /** PostgreSQL user */
  postgres_user?: string;
  /** PostgreSQL password */
  postgres_password?: string;
  /** PostgreSQL database */
  postgres_db?: string;
  /** PostgreSQL initdb args */
  postgres_initdb_args?: string;
  /** PostgreSQL host auth method */
  postgres_host_auth_method?: string;
  /** PostgreSQL conf */
  postgres_conf?: string;
  /** Clickhouse admin user */
  clickhouse_admin_user?: string;
  /** Clickhouse admin password */
  clickhouse_admin_password?: string;
  /** DragonFly password */
  dragonfly_password?: string;
  /** Redis password */
  redis_password?: string;
  /** Redis conf */
  redis_conf?: string;
  /** KeyDB password */
  keydb_password?: string;
  /** KeyDB conf */
  keydb_conf?: string;
  /** MariaDB conf */
  mariadb_conf?: string;
  /** MariaDB root password */
  mariadb_root_password?: string;
  /** MariaDB user */
  mariadb_user?: string;
  /** MariaDB password */
  mariadb_password?: string;
  /** MariaDB database */
  mariadb_database?: string;
  /** Mongo conf */
  mongo_conf?: string;
  /** Mongo initdb root username */
  mongo_initdb_root_username?: string;
  /** Mongo initdb root password */
  mongo_initdb_root_password?: string;
  /** Mongo initdb init database */
  mongo_initdb_database?: string;
  /** MySQL root password */
  mysql_root_password?: string;
  /** MySQL password */
  mysql_password?: string;
  /** MySQL user */
  mysql_user?: string;
  /** MySQL database */
  mysql_database?: string;
  /** MySQL conf */
  mysql_conf?: string;
};
