/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { UpdateApplicationByUuid409ConflictsSchema } from "./update-application-by-uuid409-conflicts-schema";

export type UpdateApplicationByUuid409 = {
  message?: string;
  warning?: string;
  conflicts?: UpdateApplicationByUuid409ConflictsSchema[];
};
