/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

/**
 * The proxy type.
 */
export type UpdateServerByUuidBodiesProxyType =
  (typeof UpdateServerByUuidBodiesProxyType)[keyof typeof UpdateServerByUuidBodiesProxyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateServerByUuidBodiesProxyType = {
  caddy: "caddy",
  none: "none",
  traefik: "traefik",
} as const;
