/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */

export type UpdateServiceByUuid200 = {
  /** Service UUID. */
  uuid?: string;
  /** Service domains. */
  domains?: string[];
};
