/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { UpdateEnvsByServiceUuidBodiesDataSchema } from "./update-envs-by-service-uuid-bodies-data-schema";

export type UpdateEnvsByServiceUuidBodies = {
  data: UpdateEnvsByServiceUuidBodiesDataSchema[];
};
