/**
 * Generated by orval v7.12.2 🍺
 * Do not edit manually.
 * Coolify
 * OpenAPI spec version: 0.1
 */
import type { UpdateEnvsByApplicationUuidBodiesDataSchema } from "./update-envs-by-application-uuid-bodies-data-schema";

export type UpdateEnvsByApplicationUuidBodies = {
  data: UpdateEnvsByApplicationUuidBodiesDataSchema[];
};
