# https://github.com/wip/action
name: WIP
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled]

jobs:
  wip:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: wip/action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
